<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*let obj = {name: "John", age: 20, subscribed: null}
        function getUserProfile (юзер) {
            return {
        name: obj.name ?? 'Аноним',
        age: obj.age ?? 18,
        subscribed: obj.subscribed ?? false,
    }
        }
        console.log(getUserProfile (obj)) */



        /*let myObj = {name: null, age: null, subscribed: null}
        function getUserProfile () { 
            let newObj = {}
            newObj.name = myObj.name ?? "Аноним"
            newObj.age = myObj.age ?? 18
            newObj.subscribed = myObj.subscribed ?? false
            console.log(newObj)
        }
        getUserProfile () */ 


        /*function checkNumber () {
        return new Promise (function(resolve, reject) {
            let randomNumber = Math.random()>0.6
            if (randomNumber) {
                resolve({success:"ok", url:'img.jpg'})
            }
            else {
                reject("Не удалось загрузить изображение")
            }
        })}
        checkNumber()
        .then(function(result) {
console.log("Получилось", result)
        })
        .catch(function(error) {
            console.error(error)
        })
        .finally(function(){
            console.log("Загрузка завершена")
        })*/ 


        /*console.log(1);//1

setTimeout(() => console.log(2));//5

Promise.resolve().then(() => console.log(3));//3

Promise.resolve().then(() => setTimeout(() => console.log(4)));//7

Promise.resolve().then(() => console.log(5));//4

setTimeout(() => console.log(6));//6

console.log(7);//2*/ 


/*Promise.resolve('Начало')
  .then((value) => {
    console.log(value); // Выводит 'Начало'
    return 'Шаг 1';
  })
  .then((value) => {
    console.log(value); // Выводит 'Шаг 1'
    throw new Error('Ошибка!');
  })
  .catch((error) => {
    console.log(error.message); // Выводит 'Ошибка!'
    return 'Обработано';
  })
  .then((value) => {
    console.log(value); // Что здесь будет выведено?
    return 'Шаг 3';
  })
  .finally(() => console.log('Готово'));*/ 



  /*async function task() {
   let promise1 = await new Promise((resolve) => setTimeout(() => resolve('Задача 1 завершена'), 1000));
   console.log(promise1)



   let promise2 = await new Promise((resolve) => setTimeout(() => resolve('Задача 2 завершена'), 500));
   console.log(promise2)


   let promise3 = await new Promise((resolve) => setTimeout(() => resolve('Задача 3 завершена'), 2000));

   console.log(promise3)
   return promise2
}

task().
then(function(result) {
    console.log(result)
})*/

/*async function showPromise() {
function promise1 () {return new Promise((resolve) => setTimeout(() => resolve('Задача 1 завершена'), 1000));}
function promise2 () {return new Promise((resolve) => setTimeout(() => resolve('Задача 2 завершена'), 500)); }
function promise3 () {return new Promise((resolve) => setTimeout(() => resolve('Задача 3 завершена'), 2000));}
let all = []
await promise1().then(function(result) {
all.push(result)})

await promise2().then(function(result) {
all.push(result)})

promise3().then(function(result) {
all.push(result)})
await new Promise (function(resolve) {
setTimeout(resolve, 2000)

})
for (let i in all) {
    console.log(all[i])
}
}
showPromise()*/ 



/*console.log('Start');

setTimeout(() => {
  console.log('setTimeout');
  Promise.resolve().then(() => console.log('Promise inside setTimeout'));
}, 0);

Promise.resolve().then(() => {
  console.log('First Promise');
  setTimeout(() => console.log('setTimeout inside Promise'), 0);
});

console.log('End');*/ 


setTimeout(function() {
    console.log(1)
})

Promise.resolve().then(function() {
    setTimeout(function(){
        console.log(2)
    })
})
    </script>
</body>
</html>